name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x ./Secur-o-Cord/gradlew
    - name: Build with Gradle
      run: ./Secur-o-Cord/gradlew build
    - name: Zip Release
      uses: TheDoctor0/zip-release@v0.2.1
    - name: git Actions
      uses: srt32/git-actions@v0.0.3
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: GradleBuild
        # Directory containing files to upload
        path: ./Secur-o-Cord/build/libs/
